
export enum ErrorCode {
  SERVER = "SERVER ERROR",
  CLIENT = "INVALID CREDENTIALS",
  NOTFOUND = "NOT FOUND",
  UNAUTHORIZED = "UNAUTHORIZED ACCESS",
  EMPTY = "NO RECORDS",
  DUPLICATE = "DUPLICATE ERROR",
  VALIDATION = "VALIDATION ERROR",
  BADREQUEST = "BAD REQUEST"
}