
export enum ErrorCode {
  SERVER = "SERVER ERROR",
  CLIENT = "INVALID CREDENTIALS",
  NOTFOUND = "NOT FOUND",
  UNAUTHORISED = "UNAUTHORISED ACCESS",
  EMPTY = "NO RECORDS",
  DUPLICATE = "DUPLICATE ERROR"
}